#! /bin/bash

#declare -a symbol_list=("1INCHBTC" "AAVEBTC" "ACMBTC" "ADABTC" "ADXBTC" "AERGOBTC" "AIONBTC" "ALGOBTC" "ALICEBTC" "ALPHABTC" "ANTBTC" "ARDRBTC" "ARKBTC" "ASTBTC" "ATOMBTC" "AUDIOBTC" "AVABTC" "AVAXBTC" "AXSBTC" "BADGERBTC" "BALBTC" "BANDBTC" "BATBTC" "BCDBTC" "BCHBTC" "BELBTC" "BLZBTC" "BNTBTC" "BQXBTC" "BRDBTC" "BTCSTBTC" "BTGBTC" "BZRXBTC" "CAKEBTC" "CELOBTC" "CHRBTC" "CHZBTC" "COMPBTC" "COTIBTC" "CRVBTC" "CTKBTC" "CTSIBTC" "CVCBTC" "DASHBTC" "DCRBTC" "DEGOBTC" "DIABTC" "DNTBTC" "DODOBTC" "DOGEBTC" "DOTBTC" "DUSKBTC" "EASYBTC" "EGLDBTC" "ELFBTC" "ENJBTC" "EOSBTC" "ETCBTC" "EVXBTC" "FETBTC" "FILBTC" "FIOBTC" "FIROBTC" "FISBTC" "FLMBTC" "FRONTBTC" "FTMBTC" "FTTBTC" "FXSBTC" "GASBTC" "GLMBTC" "GRSBTC" "GRTBTC" "GVTBTC" "GXSBTC" "HARDBTC" "HBARBTC" "HIVEBTC" "HNTBTC" "ICXBTC" "INJBTC" "IOTABTC" "JUVBTC" "KAVABTC" "KMDBTC" "KNCBTC" "KSMBTC" "LINKBTC" "LITBTC" "LRCBTC" "LSKBTC" "LTCBTC" "LTOBTC" "LUNABTC" "MANABTC" "MATICBTC" "MDABTC" "MKRBTC" "MTLBTC" "NANOBTC" "NAVBTC" "NEARBTC" "NEBLBTC" "NEOBTC" "NKNBTC" "NMRBTC" "NULSBTC" "NXSBTC" "OCEANBTC" "OGBTC" "OGNBTC" "OMBTC" "OMGBTC" "ONGBTC" "ORNBTC" "OXTBTC" "PAXGBTC" "PHABTC" "PIVXBTC" "PNTBTC" "POLYBTC" "POWRBTC" "PPTBTC" "PSGBTC" "QTUMBTC" "RDNBTC" "RENBTC" "REPBTC" "RIFBTC" "RLCBTC" "RUNEBTC" "SANDBTC" "SCRTBTC" "SFPBTC" "SKLBTC" "SKYBTC" "SNXBTC" "SOLBTC" "SRMBTC" "STEEMBTC" "STORJBTC" "STRAXBTC" "STXBTC" "SUNBTC" "SUSHIBTC" "SXPBTC" "SYSBTC" "TFUELBTC" "THETABTC" "TOMOBTC" "TRBBTC" "TVKBTC" "TWTBTC" "UNFIBTC" "UNIBTC" "UTKBTC" "VIABTC" "VIDTBTC" "WABIBTC" "WANBTC" "WAVESBTC" "WBTCBTC" "WINGBTC" "WNXMBTC" "WRXBTC" "XEMBTC" "XLMBTC" "XMRBTC" "XRPBTC" "XTZBTC" "XVSBTC" "YFIBTC" "YFIIBTC" "ZECBTC" "ZENBTC" "ZRXBTC")
#declare -a symbol_list=("1INCHUSDT" "AAVEUSDT" "ADAUSDT" "AKROUSDT" "ALGOUSDT" "ALICEUSDT" "ALPHAUSDT" "ANKRUSDT" "ATOMUSDT" "AVAXUSDT" "AXSUSDT" "BALUSDT" "BANDUSDT" "BATUSDT" "BCHUSDT" "BELUSDT" "BLZUSDT" "BNBUSDT" "BTSUSDT" "BZRXUSDT" "CHRUSDT" "CHZUSDT" "COMPUSDT" "COTIUSDT" "CRVUSDT" "CTKUSDT" "CVCUSDT" "DASHUSDT" "DODOUSDT" "DOGEUSDT" "DOTUSDT" "EGLDUSDT" "ENJUSDT" "EOSUSDT" "ETCUSDT" "FILUSDT" "FLMUSDT" "FTMUSDT" "GRTUSDT" "HBARUSDT" "HNTUSDT" "ICXUSDT" "IOSTUSDT" "IOTAUSDT" "KAVAUSDT" "KNCUSDT" "KSMUSDT" "LINKUSDT" "LITUSDT" "LRCUSDT" "LTCUSDT" "LUNAUSDT" "MANAUSDT" "MATICUSDT" "MKRUSDT" "NEARUSDT" "NEOUSDT" "OCEANUSDT" "OMGUSDT" "ONEUSDT" "ONTUSDT" "QTUMUSDT" "REEFUSDT" "RENUSDT" "RLCUSDT" "RSRUSDT" "RUNEUSDT" "RVNUSDT" "SANDUSDT" "SFPUSDT" "SKLUSDT" "SNXUSDT" "SOLUSDT" "SRMUSDT" "STMXUSDT" "STORJUSDT" "SUSHIUSDT" "SXPUSDT" "THETAUSDT" "TOMOUSDT" "TRBUSDT" "TRXUSDT" "UNFIUSDT" "UNIUSDT" "VETUSDT" "WAVESUSDT" "XEMUSDT" "XLMUSDT" "XMRUSDT" "XRPUSDT" "XTZUSDT" "YFIIUSDT" "YFIUSDT" "ZECUSDT" "ZENUSDT" "ZILUSDT" "ZRXUSDT")
declare -a symbol_list=("1INCHUSDT" "AAVEUSDT" "ADAUSDT" "AKROUSDT" "ALGOUSDT" "ALICEUSDT" "ALPHAUSDT" "ANKRUSDT" "ATOMUSDT" "AVAXUSDT" "AXSUSDT" "BALUSDT" "BANDUSDT" "BATUSDT" "BCHUSDT" "BELUSDT" "BLZUSDT" "BNBUSDT" "BTSUSDT" "BZRXUSDT" "CHRUSDT" "CHZUSDT" "COMPUSDT" "COTIUSDT" "CRVUSDT" "CTKUSDT" "CVCUSDT" "DASHUSDT" "DODOUSDT" "DOGEUSDT" "DOTUSDT" "EGLDUSDT" "ENJUSDT" "EOSUSDT" "ETCUSDT" "FILUSDT" "FLMUSDT" "FTMUSDT" "GRTUSDT" "HBARUSDT" "HNTUSDT" "ICXUSDT" "IOSTUSDT" "IOTAUSDT" "KAVAUSDT" "KNCUSDT" "KSMUSDT" "LINKUSDT" "LITUSDT" "LRCUSDT" "LTCUSDT" "LUNAUSDT" "MANAUSDT" "MATICUSDT" "MKRUSDT" "NEARUSDT" "NEOUSDT" "OCEANUSDT" "OMGUSDT" "ONEUSDT" "ONTUSDT" "QTUMUSDT" "REEFUSDT" "RENUSDT" "RLCUSDT" "RSRUSDT" "RUNEUSDT" "RVNUSDT" "SANDUSDT" "SFPUSDT" "SKLUSDT" "SNXUSDT" "SOLUSDT" "SRMUSDT" "STMXUSDT" "STORJUSDT" "SUSHIUSDT" "SXPUSDT" "THETAUSDT" "TOMOUSDT" "TRBUSDT" "TRXUSDT" "UNFIUSDT" "UNIUSDT" "VETUSDT" "WAVESUSDT" "XEMUSDT" "XLMUSDT" "XMRUSDT" "XRPUSDT" "XTZUSDT" "YFIIUSDT" "YFIUSDT" "ZECUSDT" "ZENUSDT" "ZILUSDT" "ZRXUSDT")


declare -a future_flag="-f"

if [ -d "/opt/anaconda3" ]; then
    source /opt/anaconda3/etc/profile.d/conda.sh
elif [ -d "/home/alex/anaconda3" ]; then
    source /home/alex/anaconda3/etc/profile.d/conda.sh
elif [ -d "/Users/alex/anaconda3" ]; then
    source /Users/alex/anaconda3/etc/profile.d/conda.sh
fi
conda activate Backtrader

for symbol in "${symbol_list[@]}"
do
    python calc_shots_pnl.py -e binance -s $symbol $future_flag
done

